package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.29

import (
	"context"

	"github.com/ZacxDev/zach.finance/internal/asset"
	"github.com/ZacxDev/zach.finance/internal/model"
	errs "github.com/pkg/errors"
)

// GetAsset is the resolver for the getAsset field.
func (r *queryResolver) GetAsset(ctx context.Context, tickers []string) ([]*model.Asset, error) {
	var res []*model.Asset
	for _, ticker := range tickers {
		asset, err := asset.GetStockInfo(ticker)
		if err != nil {
			return nil, errs.WithStack(err)
		}

		res = append(res, asset)
	}

	return res, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
