apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: mobl-dev
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30050
  selector:
    app: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: mobl-dev
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - image: registry:2.6.2
          name: registry
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: storage
            mountPath: /var/lib/registry
      volumes:
      - name: storage
        emptyDir: {}

