name: Deploy

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: zach-finance
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and push container image
        env:
          SCRIPT: |
            doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            doctl registry login
            bazel run //api.zach.finance/api-gateway:push_image
        run: |
          nix-channel --update
          nix-shell --run "$SCRIPT" ci/shell.nix

